import { Geist, Geist_Mono } from "next/font/google";
import { Saira_Condensed } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import AOS from "aos";
import "aos/dist/aos.css";
import AOSWrapper from "./components/AosWrapper";

const saira = Saira_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-saira-condensed",
  display: "swap",
});

export const metadata = {
  title: "Wed My Pet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={saira.variable}>
      <body className={`${saira.className} font-saira`}>
        <AOSWrapper />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
