import { Saira_Condensed } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import ClientLayout from "./components/ClientLayout";
import Image from "next/image";

const saira = Saira_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-saira-condensed",
  display: "swap",
});

export const metadata = {
  title: "Woof Woof",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={saira.variable}>
      <body className={`${saira.className} font-saira`}>
        <div className=" relative">
          <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
